### ISSUE TITLE
Hover on parent element

### ISSUE THREAD

**Issue by ianobermiller** [chenglou/RCSS#42]
Has anyone thought about how to convert the following CSS without using an event handler?

``` css
.parent {
  background: white;
}
.child {
  color: black;
}

.parent:hover {
  background: black;
}
.child:hover {
  color: white;
}
```
