### ISSUE TITLE
*zoom should be a valid CSS property name

### ISSUE THREAD

**Issue by mattferrin** [chenglou/RCSS#46]
Was experimenting to see if I can generate Bourbon Neat equivalent code.

``` css
.element {
    *zoom: 1;
    max-width: 100%;
    margin-left: auto;
    margin-right: auto;
  }
```

The above code didn't cary over.
